#!/usr/bin/env bash
# CSI Linux Signal installer / launcher
# bash ./installsignal


if ! which signal-desktop > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S wget -O- https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -
	echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" > signal-xenial.list
	echo $key | sudo -S mv signal-xenial.list /etc/apt/sources.list.d/signal-xenial.list
	echo $key | sudo -S apt update && sudo apt install signal-desktop
fi
signal-desktop
