#!/usr/bin/env python3
# Based off the tool https://github.com/rly0nheart/fbi-mostwanted

import os
import sys
import argparse
from datetime import datetime
sys.path.append(os.getcwd()+"/lib/")
sys.path.append(os.getcwd()+"/src/")
from main import *

colors = True

if not colors:
	reset = red = white = green  = ""

else:                                                 
    white = "\033[97m"
    red = "\033[91m"    
    reset = "\033[0m"
    green = "\033[92m"
    #yellow = "\033[93m"


if __name__ == '__main__':
    while True:
        try:
        	Wanted(args).on_connection()
        	break
        	
        except KeyboardInterrupt:
        	if args.verbose:
        		print(f'\n{white}[{red}x{white}] Process interrupted with {red}Ctrl{white}+{red}C{reset}')
        		break
        	break
        	
        except Exception as e:
        	if args.verbose:
        		print(f'{white}[{red}!{white}] Error: {red}{e}{reset}')
    
    if args.verbose:
    	exit(f'{white}[{green}-{white}] Finished in {green}{datetime.now()-start_time}{white} seconds.{reset}')
